# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        jdk: ["8", "11", "17", "21"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
        cache: 'maven'
    - name: MVN Install
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V
    - name: Build
      run: mvn clean compile -U
    - name: Unit Tests
      run: mvn test -Punit-tests 
    - name: Integration Tests
      run: mvn test -Pintegration-tests
